name: "Update a Drupal 8+ remote instance"
description: 'SSH to server and execute Drush update commands on the Drupal 8+ instance'
inputs:
  path:
    description: 'Absolute path on the server where the instance is located'
    required: true
  server_name:
    description: 'Name of the server SSH name'
    required: true
    default: 'server'
  drush:
    description: 'Path to drush executable'
    required: false
    default: './vendor/bin/drush'
  enable_extra_modules:
    description: 'A space-separated list of modules to be enabled after the deployment is complete. Modules must be installed in Drupal'
    required: false
  enable_maintenance_mode:
    description: 'Toggles maintenance mode during the deployment. Default value "true" enables the maintenance mode.'
    required: false
    default: 'true'
  statuscake_api_key:
    description: 'API key for StatusCake'
    required: false
  statuscake_test_id:
    description: 'Test ID in StatusCake'
    required: false

runs:
  using: "composite"
  steps:
    - name: 'Disable StatusCake monitoring'
      if: ${{ inputs.statuscake_api_key != '' && inputs.statuscake_test_id != '' }}
      shell: bash
      run: |
        echo "Disabling StatusCake monitoring..."
        IFS=',' read -ra IDS <<< "${{ inputs.statuscake_test_id }}"
        for id in "${IDS[@]}"; do
          echo "Disabling StatusCake monitoring for ID: $id"
          curl -X PUT "https://api.statuscake.com/v1/uptime/$id" \
            -H "Authorization: Bearer ${{ inputs.statuscake_api_key }}" \
            -d 'paused=true'
        done

    - name: "Update Drupal instance"
      shell: bash
      run: |
        ssh ${{ inputs.server_name }} 'if [ "${{ inputs.enable_maintenance_mode }}" == "true" ]; then cd ${{ inputs.path }} && ${{ inputs.drush }} state-set system.maintenance_mode TRUE; fi'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} updatedb -y'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} cache:rebuild'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} config-import -y'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} updatedb -y'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} cache:rebuild'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} deploy:hook -y'
        ssh ${{ inputs.server_name }} 'if [ "${{ inputs.enable_extra_modules }}" != "" ]; then cd ${{ inputs.path }} && ${{ inputs.drush }} pm:enable ${{ inputs.enable_extra_modules }}; fi'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} cache:rebuild'
        ssh ${{ inputs.server_name }} 'if [ "${{ inputs.enable_maintenance_mode }}" == "true" ]; then cd ${{ inputs.path }} && ${{ inputs.drush }} state-set system.maintenance_mode FALSE; fi'

    - name: 'Enable StatusCake monitoring'
      if: ${{ always() && inputs.statuscake_api_key != '' && inputs.statuscake_test_id != '' }}
      shell: bash
      run: |
        echo "Enabling StatusCake monitoring..."
        IFS=',' read -ra IDS <<< "${{ inputs.statuscake_test_id }}"
        for id in "${IDS[@]}"; do
          echo "Enabling StatusCake monitoring for ID: $id"
          curl -X PUT "https://api.statuscake.com/v1/uptime/$id" \
            -H "Authorization: Bearer ${{ inputs.statuscake_api_key }}" \
            -d 'paused=false'
        done
