name: "Update a Drupal 8+ remote instance"
description: 'SSH to server and execute Drush update commands on the Drupal 8+ instance'
inputs:
  path:
    description: 'Absolute path on the server where the instance is located'
    required: true
  server_name:
    description: 'Name of the server SSH name'
    required: true
    default: 'server'
  drush:
    description: 'Path to drush executable'
    required: false
    default: './vendor/bin/drush'
  enable_extra_modules:
    description: 'A space-separated list of modules to be enabled after the deployment is complete. Modules must be installed in Drupal'
    required: false
  enable_maintenance_mode:
    description: 'Toggles maintenance mode during the deployment. Default value "true" enables the maintenance mode.'
    required: false
    default: 'true'
  api_key_statuscake:
    description: 'API key for StatusCake'
    required: false
  test_id_statuscake:
    description: 'Test ID in StatusCake'
    required: false

runs:
  using: "composite"
  steps:
    - name: 'Disable StatusCake monitoring (if applicable)'
      shell: bash
      run: |
        if [ -n "${{ inputs.api_key_statuscake }}" ] && [ -n "${{ inputs.test_id_statuscake }}" ]; then
          echo "Disabling StatusCake monitoring..."
          curl -X PUT "https://api.statuscake.com/v1/uptime/${{ inputs.test_id_statuscake }}" \
            -H "Authorization: Bearer ${{ inputs.api_key_statuscake }}" \
            -d 'paused=true'
        else
          echo "StatusCake credentials not provided. Skipping monitor disable."
        fi

    - name: "Update Drupal instance"
      shell: bash
      run: |
        ssh ${{ inputs.server_name }} 'if [ "${{ inputs.enable_maintenance_mode }}" == "true" ]; then cd ${{ inputs.path }} && ${{ inputs.drush }} state-set system.maintenance_mode TRUE; fi'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} updatedb -y'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} cache:rebuild'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} config-import -y'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} updatedb -y'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} cache:rebuild'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} deploy:hook -y'
        ssh ${{ inputs.server_name }} 'if [ "${{ inputs.enable_extra_modules }}" != "" ]; then cd ${{ inputs.path }} && ${{ inputs.drush }} pm:enable ${{ inputs.enable_extra_modules }}; fi'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} cache:rebuild'
        ssh ${{ inputs.server_name }} 'if [ "${{ inputs.enable_maintenance_mode }}" == "true" ]; then cd ${{ inputs.path }} && ${{ inputs.drush }} state-set system.maintenance_mode FALSE; fi'

    - name: 'Enable StatusCake monitoring (if applicable)'
      if: always()
      shell: bash
      run: |
        if [ -n "${{ inputs.api_key_statuscake }}" ] && [ -n "${{ inputs.test_id_statuscake }}" ]; then
          echo "Enabling StatusCake monitoring..."
          curl -X PUT "https://api.statuscake.com/v1/uptime/${{ inputs.test_id_statuscake }}" \
            -H "Authorization: Bearer ${{ inputs.api_key_statuscake }}" \
            -d 'paused=false'
        else
          echo "StatusCake credentials not provided. Skipping monitor re-enable."
        fi
